### ISSUE TITLE
Cron failures: Invalid JWT Signature

### ISSUE THREAD

**Issue by hugovk** [di/pyreadiness#20]
The last two cron runs failed:

* https://github.com/di/pyreadiness/actions/runs/1331179091
* https://github.com/di/pyreadiness/actions/runs/1335507119

This line:
```python
    for row in bq_client.query(QUERY.format(major=major)).result()
```

causes:
```
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', ***'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'***)
```

Full traceback:

```
Traceback (most recent call last):
Fetching top projects
  File "/home/runner/work/pyreadiness/pyreadiness/main.py", line 144, in <module>
    run(None, write_file=write_local_file)
  File "/home/runner/work/pyreadiness/pyreadiness/main.py", line 111, in run
    projects = fetch_top_projects()
  File "/home/runner/work/pyreadiness/pyreadiness/main.py", line 81, in fetch_top_projects
    projects = ***
  File "/home/runner/work/pyreadiness/pyreadiness/main.py", line 84, in <dictcomp>
    for row in bq_client.query(QUERY.format(major=major)).result()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 1372, in query
    query_job._begin(retry=retry)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/cloud/bigquery/job.py", line 552, in _begin
    api_response = client._call_api(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/cloud/bigquery/client.py", line 363, in _call_api
    return call()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/api_core/retry.py", line 286, in retry_wrapped_func
    return retry_target(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/cloud/_http.py", line 288, in api_request
    response = self._make_request(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/cloud/_http.py", line 183, in _make_request
    return self._do_request(method, url, headers, data, target_object)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/cloud/_http.py", line 211, in _do_request
    return self.http.request(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/auth/transport/requests.py", line 476, in request
    self.credentials.before_request(auth_request, method, url, request_headers)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/auth/credentials.py", line 133, in before_request
    self.refresh(request)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/oauth2/service_account.py", line 408, in refresh
    access_token, expiry, _ = _client.jwt_grant(
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/oauth2/_client.py", line 193, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/oauth2/_client.py", line 165, in _token_endpoint_request
    _handle_error_response(response_data)
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_data)
google.auth.exceptions.RefreshError: ('invalid_grant: Invalid JWT Signature.', ***'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'***)
```

**Comment by hugovk** [comment]
Suggestion from https://github.com/googleapis/google-cloud-python/issues/3100#issuecomment-924226353:

> I was getting this error. Turns out it had been too long since I'd run `gcloud auth activate-service-account` and my credentials had expired
